### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by pmb59** [Tj-Stockopedia/action-get-changed-folders#59]
Many thanks for the GitHub Action. Would it be possible to add some examples?

**Comment by pmb59** [comment]
In addition, should 'csv of newline' be 'csv **or** newline'?

**Comment by tjbroodryk** [comment]
Hi, thanks for raising the issue, and good spot in the `readme` - i've fixed the typo!

Was there any specific examples your were after? 

I've created a PR here with an example https://github.com/Stockopedia/action-get-changed-files/pull/64 - i'd welcome your feedback!

**Comment by pmb59** [comment]
LGTM thanks!

**Comment by tjbroodryk** [comment]
awesome, thanks!
