### ISSUE TITLE
authentication request/ error

### ISSUE THREAD

**Issue by pmb59** [Tj-Stockopedia/action-get-changed-folders#67]
Hi, when I clone the repo

`git clone https://github.com/Stockopedia/get-changed-files  `

it asks for authentication. Is this expected?

Best wishes,

**Comment by pmb59** [comment]
Could it be that in some part of your action you are doing

`git clone 'https://github.com/Stockopedia/get-changed-files`

instead of

`git clone 'https://github.com/Stockopedia/action-get-changed-files`

**Comment by tjbroodryk** [comment]
Hmm, `git clone https://github.com/Stockopedia/action-get-changed-files` should work - i dont think `https://github.com/Stockopedia/get-changed-files` is a valid repo
